# Permalinks
permalink:           pretty

# Setup
title:               Eugene Kirillov
tagline:             'Senior Software Engineer'
description:         'Software developer'
paginate:            10
excerpt_separator:   <!--more-->

plugins:
  - jekyll-mentions
  - jekyll-paginate
